name: scanforge_3d
description: ScanForge 3D - simulation de pipeline de scan 3D mobile.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  model_viewer_plus: ^1.9.1
  permission_handler: ^11.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
